language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: first-nodejs-95-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: puExT8kAwf/gLuqNMwwV6Ep48qUbeQLyeYlqjD6jsduDKuEvBCHC2Yfx0ksSS+aiQl2XqFxfEqEJt6S/Eqvjh02YA0x1XZcw9wHUAbeiVkr6anvyuHaV+xccYiGyPr9a4WRKHZsGjJ2LM2kPMizt5EzYJ5rjW4l5qfT/VOQVJ5quNehanEZGlPRJiA+uU0/gJC+W3BmtAbNlrif9EiFvHsRjDKNj4Ga4OekqVGbwP+/UqBXnAlWgTuVp58Boe4BC1mtkRaQpQMrbw8jI6ES28mR/+q5FoaG4f88J7hE4co9W3I+EeZY82cjLPrDP363wxD2d5YgAIS0LodUjC6EFS/T2bYj8T+PjgzlxUX/+Lgsfqz0BOd/q9kMfgLQUjZ3KloJiYW0wTd0XoRXT6AlEdnPZLPho6z1NQacdae4ERlAmJ2umDqUeIA6UDveNgLVYGmATLG13OMlNYPOycWL34UwENhZ21R6RpUrI334EoJT11ulyLlIMMHVGXgZYp1CK2jbmYXFTWCfxjdbhnmqHe6gcW1kwofngN993hxoJyPU64AzxPseDuAP5eg4SQrjZyJ4w2NpblsJOKrUGJlQ+1hBpc6s47w+ih2T5+pGDxo/PasCGXTn/+GCBsMESMe42nBaNknO9UIdGA7RPafv7G/Q60glahccgMn3pu9uAOn4=
