language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: first-nodejs-95-app
  api_key:
    secure: Ilkv3XRNQlum9u192lFGgTqOQEIx/ZVDkx8BZQmUJRLqvWzkVpY+ROquAWFbE6LgRRSHO/Q0DRRc74QJiPuLCCpn7ipT7lEuUDU8haj21t2jgH0KG02B4OrQ8ScRMLvzXtjvm2BTUvffSFL5+HfbzQ1oa94sz1Nmf82Zs5qR1AVvbijNzUrpD798PZoolJdVC3n5nuRQFRJ/0UoShdBwheQqExghfNTFhrfL+fhie8AeLUiMqLBZ55B/aznnMwM8YffCpUbe+oWyohygLpexPMq5BuedGWcLdDEUIvxHG6kQOW2Q224ApRrSVojfl+nDQYM4ZsObQVu31B3P7I6IZEJm2UwTjt/NoA0ILDyhcriudpfjBj2/g7Kn7/WoOj1Ijx7Q4JA2g/aodYF4Ig4+8n7VQh9rVnr3KTPJQ0DFwGZxxXoukfFXn5EtRboRRFzpC+vdBmVoiIamLDWc7iUIgl97OeuIGJ9cvbqZUv9X0IEZ5DKL9QRBgmWt2S0HwsLJiU2uFSvHODQoWKaZvlNlpRKH2h0FY/FIaCfrNvX3s7CfjXdC5pdDZWztRJNtQoAF03fNUMp1XaTPmC/yIlrEXu9THfXqV4OxqFc2cwmTISMZ7s7vu5ZkusEdh1E1mTytHtNSjhKtRcr+CgRvbmZWMt2rjpY9ldKJpDuONwTHJzc=
