language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: first-nodejs-95-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: RfSBjx6Q9QbMVHhgEGZb+8GCBG+FkRTT8bZI1spihHj7bB6tVn55zQxNOEFG54KVW6HL/Y0mWoURU7pOBN6npCAtx4a84W0lbl26H7lQSMDfuAHoyNi5JwtmXAlR+ZuA9RcKEYxRTPSq2yey+rq3vPbRVJ/Z2hTmpzqS7CipyDrwxQ6DiWTRUw5HekEjCPunl9eMyx+COBWkIy7YqNPAW5VOMImGO+cEmYLi5hzlBqbN6qnx0KV2EDqlhHkT7aJo9FeaCKbFVUqeD6L8bPujvtYid+L4eX4d6azTo/Kakzm8rDZxdQmW1kbCoArUrAwT8v8aMNjsyrRezenUjKKOSwx66jHNV6odkOVXlGx5yWKC4lgVOuOJRkoN7UL5pNoFPRtBVIbDtfiZxcQfsHwk5Z9KthEkso5yP6XCtl2NtmmkPRxKxV5rud1Jdunt4qv00mUogtyA3VjOvF+miFmCEQ5YnGNnmDPrhK45CNhRdCDR29AdJs+HxsversYSedhRzHF73Mc5wOAMLHpX0njXQBiUz2Kr80UNPSdru7/gg/N1VfXOUjCuoaqZsRHOSpIdc7FtMwt+xTWnCQ+2IqsEwCGFAJ2tmSqVVf1EesQ0xMgeTg8N2jRmAKjtN3mlrT967F/xn7vl/W/BsgBH8GtS1UMW82sIz3Qjm7IIm6rtrpg=
