language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
  # before_deploy:
  #   - npm run build-client # make the bundle
  #   - rm -rf node_modules # omit from the tarball, since we skip cleanup
  # deploy:
  #   skip_cleanup: true # prevents travis from deleting the build
  #   provider: heroku
  #   app: first-nodejs-95-app # see README
  # api_key:
  #   secure: YOUR-***ENCRYPTED***-API-KEY-HERE
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: first-nodejs-95-app
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: aK6LfjHxB/LJz6Wbvpc4o6cKQGD1gYIsZdNv9HlHzcfJW99cC/eaB3YpX8jVIZepXEegQvM1sL97CbpmbVxk/lhOmRoJyrU/IaRqloME+4kYnY5VnE/bHAuTDJS8gIQRZEG+QwuO+AsSF9HolVKTi+vaMfZvwH4GWZbku6psebde05yY10Z6pNkiu02p59EM76ihifAqVn/nPlXYUsjc8Qdm3BApQW4KAVuj8AWob+wk63tLvRcQsAtju/tcMClsR0rgfg3/HdIiG10tGYqQg9x6co7Fny+Y/Hl2o+MN6jSgWE3/woxjq9+TfT6M62LG7m795cgP6DwbVTM1X0wb0ew1h2ssoYHNkBJoS2PncferBU4W8o7+KxM/XB1v24ZrmUv3sKIRwfre0xWPL1sBAJ3jHUPfk8dCbk0+NrPb0rT7yhkYN+M7HQdiTOpCkA76kMgxEgH1VM+eu9z1u7JKsYpdcfjfKSSF88CLGbWjvBnhgQdUA9c16d1G8EJdpt0TWf1zAUV59x4qKDjpCz5Jm6dvd2zogvtS+UfUaWElTXcaTX+kM0cFgihJsHKMSzH/gDce/m+9ZqdU1VmAZyHfur42D5SKWP1GhWQwxjcltRUYhfN0IeRgfKaqRvHOjiWvten5vVQM3JJv8NwuxwF2Qt/6GxgvtJTMsGNit60xykE=
